### ISSUE TITLE
my app freezes after start

### ISSUE THREAD

**Issue by humbertocruz** [pmwisdom/meteor-background-geolocation-services#4]
Hi, I´m try to use it with meteor but I can´t figure out how to do it. I can´t test it on web and my phone app freezes on BackgroundLocation.start

well, first, where should I run it ? ( client, server or both ? ). i put the BackgroundLocation.configure on client startup, seens ok

after, when the user start a process on the app,  it calls BackgroundLocation.start() and nothing more happens, need to close and open the app again.

i made it working with the foreground geolocation but I will realy need to continue getting location with the screen locked

thanks for any help

**Comment by lmaddio** [comment]
I am not having this issue, how you init your app?
Code must be in client side.
I make a file in client's folder where I place a "init.js" which has initialization options as this plugin.

**Comment by pmwisdom** [comment]
@humbertocruz If you supply some example code that would be helpful.

Initialization / starting must happen on the client, after Meteor.startup has fired.

**Comment by humbertocruz** [comment]
hello... I start over and it´s not stopping any more. Thanks... I'm adjusting the filters and using both foreground and background plugins.
